cmake_minimum_required(VERSION 3.12)
project(memtailor-consumer LANGUAGES CXX)
find_package(memtailor 1.4 CONFIG REQUIRED)
add_executable(consumer consumer.cpp)
target_link_libraries(consumer PRIVATE memtailor::memtailor)
if(EXPECT_MEMT_DEBUG)
  target_compile_definitions(consumer PRIVATE EXPECT_MEMT_DEBUG)
endif()
enable_testing()
add_test(NAME installed-consumer COMMAND consumer)
